### ISSUE TITLE
Permission needed in android API 33

### ISSUE THREAD

**Issue by sidAli1993** [mahdiasd/BottomDialogFilePicker#5]
I am getting 'permission needed' toast in android 13 or API 33 emulator, even i manually check the permissions are enabled properly.

No logs nothing.

**Comment by sidAli1993** [comment]
{.GrantPermissionsActivity}: Setting back callback null


{.GrantPermissionsActivity (client)' was disposed without first being removed with the input manager!


these two lines of log i found , please fix it, i almost use your lib in my whole project but now facing this :( lolx

**Comment by mahdiasd** [comment]
Hello, I hope you are well. I am glad that you are using my library.
I tested it on Android 13 and it runs without problems and if the permissions are received correctly, the permission need message does not appear.

I know that you said that you checked and the permissions are set, but check again from the application settings section that all permissions are correctly activated.

Also, make sure that the problem is not with the emulator.

Deleting the app and reinstalling it may also help.

You can also take a clone of my project and install it on the emulator to see if it still has this problem.

**Comment by mahdiasd** [comment]
And also make sure that you have added these two lines in the project manifest:

    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

    <uses-permission android:name="android.permission.CAMERA" />

**Comment by sidAli1993** [comment]
thank you mahdi for your response,
i am sending you a video please see...
I have enabled all of the permissions but see what it is saying

**Comment by sidAli1993** [comment]
i am giving all of these permissions

private val PERMISSIONS = arrayOf<String>(
    CAMERA,
    READ_EXTERNAL_STORAGE,
    WRITE_EXTERNAL_STORAGE,
    READ_MEDIA_AUDIO,
    READ_MEDIA_VIDEO,
    READ_MEDIA_IMAGES,
)

**Comment by sidAli1993** [comment]
I have checked in android 32 , it only have problem in android api 33 or
android 13, All of the permissions are enabled
manually,programmatically etc..

**Comment by sidAli1993** [comment]
Well mahdi I implement it by by-passing your permissions check , there is
some problem in your request permission etc..

It is working now..
JAZAKALLAH

**Comment by sidAli1993** [comment]
[image: image.png]

**Comment by mahdiasd** [comment]
Oh, I see where the problem is

You set targetSdk to 33
And because of the changes in Android 13 permissions, this problem appeared.

You can read this article to find out:
https://medium.com/@maydin/how-to-migrate-read-external-storage-permission-to-read-media-images-permission-for-
android-13-ab99de39318

If you add these permissions, the problem should probably be solved. 

Anyway, whenever I find free time, I will definitely update the code.
Let me know if your problem is solved or not.

**Comment by sidAli1993** [comment]
Yes thank you

**Comment by mahdiasd** [comment]
Good Lock Ali
